# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\caver\Documents\GitHub\launcher\designer\launcher.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_launcher(object):
    def setupUi(self, launcher):
        launcher.setObjectName("launcher")
        launcher.resize(778, 629)
        launcher.setMouseTracking(True)
        self.caltopoButton = QtWidgets.QPushButton(launcher)
        self.caltopoButton.setGeometry(QtCore.QRect(30, 20, 180, 180))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.caltopoButton.sizePolicy().hasHeightForWidth())
        self.caltopoButton.setSizePolicy(sizePolicy)
        self.caltopoButton.setMinimumSize(QtCore.QSize(180, 180))
        self.caltopoButton.setMaximumSize(QtCore.QSize(180, 180))
        self.caltopoButton.setBaseSize(QtCore.QSize(180, 180))
        self.caltopoButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.caltopoButton.setMouseTracking(True)
        self.caltopoButton.setText("")
        self.caltopoButton.setFlat(True)
        self.caltopoButton.setObjectName("caltopoButton")
        self.radiologButton = QtWidgets.QPushButton(launcher)
        self.radiologButton.setGeometry(QtCore.QRect(30, 210, 180, 180))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radiologButton.sizePolicy().hasHeightForWidth())
        self.radiologButton.setSizePolicy(sizePolicy)
        self.radiologButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radiologButton.setMouseTracking(True)
        self.radiologButton.setFlat(True)
        self.radiologButton.setObjectName("radiologButton")
        self.iapbButton = QtWidgets.QPushButton(launcher)
        self.iapbButton.setGeometry(QtCore.QRect(30, 400, 180, 180))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iapbButton.sizePolicy().hasHeightForWidth())
        self.iapbButton.setSizePolicy(sizePolicy)
        self.iapbButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.iapbButton.setMouseTracking(True)
        self.iapbButton.setFlat(True)
        self.iapbButton.setObjectName("iapbButton")
        self.textEdit = QtWidgets.QTextEdit(launcher)
        self.textEdit.setGeometry(QtCore.QRect(240, 210, 521, 391))
        self.textEdit.setObjectName("textEdit")
        self.caltopoButtonWidget = QtWidgets.QWidget(launcher)
        self.caltopoButtonWidget.setGeometry(QtCore.QRect(30, 20, 180, 180))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.caltopoButtonWidget.sizePolicy().hasHeightForWidth())
        self.caltopoButtonWidget.setSizePolicy(sizePolicy)
        self.caltopoButtonWidget.setMinimumSize(QtCore.QSize(150, 150))
        self.caltopoButtonWidget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.caltopoButtonWidget.setMouseTracking(True)
        self.caltopoButtonWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.caltopoButtonWidget.setAutoFillBackground(False)
        self.caltopoButtonWidget.setStyleSheet("image: url(:/launcher/icons/caltopo_logo.svg);")
        self.caltopoButtonWidget.setObjectName("caltopoButtonWidget")
        self.radiologButtonWidget = QtWidgets.QWidget(launcher)
        self.radiologButtonWidget.setGeometry(QtCore.QRect(30, 210, 180, 180))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radiologButtonWidget.sizePolicy().hasHeightForWidth())
        self.radiologButtonWidget.setSizePolicy(sizePolicy)
        self.radiologButtonWidget.setMinimumSize(QtCore.QSize(150, 150))
        self.radiologButtonWidget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radiologButtonWidget.setMouseTracking(True)
        self.radiologButtonWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.radiologButtonWidget.setAutoFillBackground(False)
        self.radiologButtonWidget.setStyleSheet("image: url(:/launcher/icons/radiolog.svg);")
        self.radiologButtonWidget.setObjectName("radiologButtonWidget")
        self.iapbButtonWidget = QtWidgets.QWidget(launcher)
        self.iapbButtonWidget.setEnabled(True)
        self.iapbButtonWidget.setGeometry(QtCore.QRect(30, 400, 180, 180))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iapbButtonWidget.sizePolicy().hasHeightForWidth())
        self.iapbButtonWidget.setSizePolicy(sizePolicy)
        self.iapbButtonWidget.setMinimumSize(QtCore.QSize(150, 150))
        self.iapbButtonWidget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.iapbButtonWidget.setMouseTracking(True)
        self.iapbButtonWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.iapbButtonWidget.setAutoFillBackground(False)
        self.iapbButtonWidget.setStyleSheet("image: url(:/launcher/icons/IAPBuilder.svg);")
        self.iapbButtonWidget.setObjectName("iapbButtonWidget")
        self.caltopoTrayWidget = QtWidgets.QWidget(launcher)
        self.caltopoTrayWidget.setGeometry(QtCore.QRect(130, 40, 601, 141))
        self.caltopoTrayWidget.setMouseTracking(True)
        self.caltopoTrayWidget.setStyleSheet("#caltopoTrayWidget {\n"
"    border:3px outset green;\n"
"}")
        self.caltopoTrayWidget.setObjectName("caltopoTrayWidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.caltopoTrayWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(129, 9, 461, 121))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.caltopoWebButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.caltopoWebButton.sizePolicy().hasHeightForWidth())
        self.caltopoWebButton.setSizePolicy(sizePolicy)
        self.caltopoWebButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.caltopoWebButton.setStyleSheet("image: url(:/launcher/icons/caltopo_web.svg);")
        self.caltopoWebButton.setText("")
        self.caltopoWebButton.setFlat(True)
        self.caltopoWebButton.setObjectName("caltopoWebButton")
        self.horizontalLayout.addWidget(self.caltopoWebButton)
        self.caltopoLANButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.caltopoLANButton.sizePolicy().hasHeightForWidth())
        self.caltopoLANButton.setSizePolicy(sizePolicy)
        self.caltopoLANButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.caltopoLANButton.setMouseTracking(True)
        self.caltopoLANButton.setStyleSheet("image: url(:/launcher/icons/caltopo_lan.svg);")
        self.caltopoLANButton.setText("")
        self.caltopoLANButton.setFlat(True)
        self.caltopoLANButton.setObjectName("caltopoLANButton")
        self.horizontalLayout.addWidget(self.caltopoLANButton)
        self.caltopoLocalhostButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.caltopoLocalhostButton.sizePolicy().hasHeightForWidth())
        self.caltopoLocalhostButton.setSizePolicy(sizePolicy)
        self.caltopoLocalhostButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.caltopoLocalhostButton.setStyleSheet("image: url(:/launcher/icons/caltopo_local.svg);")
        self.caltopoLocalhostButton.setText("")
        self.caltopoLocalhostButton.setFlat(True)
        self.caltopoLocalhostButton.setObjectName("caltopoLocalhostButton")
        self.horizontalLayout.addWidget(self.caltopoLocalhostButton)
        self.caltopoWebButton.raise_()
        self.caltopoLocalhostButton.raise_()
        self.caltopoLANButton.raise_()
        self.trayCoverWidget = QtWidgets.QWidget(launcher)
        self.trayCoverWidget.setGeometry(QtCore.QRect(0, 29, 141, 161))
        self.trayCoverWidget.setAutoFillBackground(True)
        self.trayCoverWidget.setStyleSheet("color:gray;")
        self.trayCoverWidget.setObjectName("trayCoverWidget")
        self.caltopoTrayWidget.raise_()
        self.trayCoverWidget.raise_()
        self.textEdit.raise_()
        self.caltopoButton.raise_()
        self.radiologButton.raise_()
        self.iapbButton.raise_()
        self.caltopoButtonWidget.raise_()
        self.radiologButtonWidget.raise_()
        self.iapbButtonWidget.raise_()

        self.retranslateUi(launcher)
        self.caltopoButton.clicked.connect(launcher.caltopoClicked) # type: ignore
        self.radiologButton.clicked.connect(launcher.radiologClicked) # type: ignore
        self.iapbButton.clicked.connect(launcher.iapbClicked) # type: ignore
        self.caltopoLANButton.clicked.connect(launcher.caltopoLANClicked) # type: ignore
        self.caltopoWebButton.clicked.connect(launcher.caltopoWebClicked) # type: ignore
        self.caltopoLocalhostButton.clicked.connect(launcher.caltopoLocalhostClicked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(launcher)

    def retranslateUi(self, launcher):
        _translate = QtCore.QCoreApplication.translate
        launcher.setWindowTitle(_translate("launcher", "NCSSAR Application Launcher"))
        self.textEdit.setHtml(_translate("launcher", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">SARTopo - Web, Trailer Server, or Localhost</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Web</span><span style=\" font-size:8pt;\"> - sartopo.com - if you expect to have very reliable and reasonably fast internet for the entire operation</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Trailer Server</span><span style=\" font-size:8pt;\"> - NCSSAR uses this most of the time- if you want to use an online map, but, your internet connection is not fast or is unreliable</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Localhost</span><span style=\" font-size:8pt;\"> - if you need to use this computer without internet or trailer server connection</span></p></body></html>"))
import launcher_rc
